trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 1️⃣ Download Secure File (publish profile, if needed)
- task: DownloadSecureFile@1
  name: DownloadPublishProfile
  inputs:
    secureFile: 'devops-site-profile'  # must match the uploaded secure file name exactly

# 2️⃣ Copy all site files to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*'    # all files, not just .html
    TargetFolder: '$(Build.ArtifactStagingDirectory)/site'

# 3️⃣ Archive files into a zip for deployment
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop/site.zip'
    replaceExistingArchive: true

# 4️⃣ Publish the build artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'

# 5️⃣ Deploy to Azure Web App using zipDeploy
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureConnection' # Service connection name in Azure DevOps
    appName: 'devops-site'
    package: '$(Build.ArtifactStagingDirectory)/drop/site.zip'
    deploymentMethod: 'zipDeploy'
